HyperPara:
  Decom_lr: 0.0001
  Decom_prefix: 'checkpoints/Decom/'
  Restor_lr: 0.0001
  Restor_prefix: 'checkpoints/Restor/'
  Adjust_lr: 0.0001
  Adjust_prefix: 'checkpoints/Adjust/'
Dataset:
  input_path: '/media/haiya/tr_data2/fivek/input'
  label_path: '/media/haiya/tr_data2/fivek/E'
  test_input_path: '/media/haiya/tr_data2/fivek/input'
  test_label_path: '/media/haiya/tr_data2/fivek/E'
  filelist: 'filelist.json'
  num_parallel_calls: 6
  buffer_size: 20
  shuffle: 48
  batch_size_Decom: 10
  patch_size_Decom: 48
  batch_size_Restor: 4
  patch_size_Restor: 384
  batch_size_Adjust: 10
  patch_size_Adjust: 48

