HyperPara:
  Decom_lr: 0.0001
  Decom_prefix: 'checkpoints/Decom/'
  Restor_lr: 0.0001
  Restor_prefix: 'checkpoints/Restor/'
  Adjust_lr: 0.0001
  Adjust_prefix: 'checkpoints/Adjust/'

  batch_size_Decom: &batch_size_Decom 20
  patch_size_Decom: &patch_size_Decom 144
  batch_size_Restor: &batch_size_Restor 6
  patch_size_Restor: &patch_size_Restor 386
  batch_size_Adjust: &batch_size_Adjust 20
  patch_size_Adjust: &patch_size_Adjust 144
Dataset:
  train_input_path: '/media/haiya/tr_data2/fivek/input'
  train_lable_path: '/media/haiya/tr_data2/fivek/E'
  test_input_path: '/media/haiya/tr_data2/fivek/input'
  test_lable_path: '/media/haiya/tr_data2/fivek/E'
  filelist: 'filelist.json'
  num_parallel_calls: 6
  buffer_size: 100
  shuffle: 48
  batch_size_Decom: *batch_size_Decom
  patch_size_Decom: *patch_size_Decom
  batch_size_Restor: *batch_size_Restor
  patch_size_Restor: *patch_size_Restor
  batch_size_Adjust: *batch_size_Adjust
  patch_size_Adjust: *patch_size_Adjust

